//
// Created by zeyad-osama on 09/01/2021.
//

#ifndef JSON_CPP_LIB_VARS_VERSION_H
#define JSON_CPP_LIB_VARS_VERSION_H

#define JSON_CPP_VERSION_MAJOR 1
#define JSON_CPP_VERSION_MINOR 0
#define JSON_CPP_VERSION_PATCH 0

#define JSON_CPP_VERSION \
	(((JSON_CPP_VERSION_MAJOR)*10000000) + ((JSON_CPP_VERSION_MINOR)*100000) \
	 + (JSON_CPP_VERSION_PATCH))

#endif //JSON_CPP_LIB_VARS_VERSION_H